apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  namespace: kubevirt
  name: myvmi
spec:
  terminationGracePeriodSeconds: 5
  domain:
    resources:
      requests:
        memory: 64M
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: cloudinitdisk
        disk:
          bus: virtio
  volumes:
    - name: containerdisk
      containerDisk:
        image: kubevirt/cirros-container-disk-demo:latest
    - name: cloudinitdisk
      cloudInitNoCloud:
        userData: |
          ssh-authorized-keys:
            - ssh-rsa I2Nsb3VkLWNvbmZpZwoKI3BhY2thZ2VfdXBncmFkZTogdHJ1ZQoKI3BhY2thZ2VzOgojICAtIGdpdAojICAtIHhyZHAKIyAgLQoKI3J1bmNtZDoKICMtIFsgc2gsIC1jLCAieXVtIGdyb3VwaW5zdGFsbCAteSAnR05PTUUgRGVza3RvcCcgJ0dyYXBoaWNhbCBBZG1pbmlzdHJhdGlvbiBUb29scyciIF0KICMtIFsgc2gsIC1jLCAibG4gLXNmIC9saWIvc3lzdGVtZC9zeXN0ZW0vcnVubGV2ZWw1LnRhcmdldCAvZXRjL3N5c3RlbWQvc3lzdGVtL2RlZmF1bHQudGFyZ2V0IiBdCiAjLSBbIHNoLCAtYywgInJwbSAtVXZoIGh0dHBzOi8vZGwuZmVkb3JhcHJvamVjdC5vcmcvcHViL2VwZWwvZXBlbC1yZWxlYXNlLWxhdGVzdC03Lm5vYXJjaC5ycG0iIF0KICMtIFsgc2gsIC1jLCAieXVtIC15IGluc3RhbGwgeHJkcCB0aWdlcnZuYy1zZXJ2ZXIiIF0KICMtIFsgc2gsIC1jLCAic3lzdGVtY3RsIHN0YXJ0IHhyZHAiIF0KICMtIFsgc2gsIC1jLCAic3lzdGVtY3RsIGVuYWJsZSB4cmRwIiBdCiAjLSBbIHNoLCAtYywgInN5c3RlbWN0bCBlbmFibGUgZmlyZXdhbGxkIiBdCiAjLSBbIHNoLCAtYywgInN5c3RlbWN0bCBzdGFydCBmaXJld2FsbGQiIF0KICMtIFsgc2gsIC1jLCAiZmlyZXdhbGwtY21kIC0tcGVybWFuZW50IC0tYWRkLXBvcnQ9MzM4OS90Y3AiIF0KICMtIFsgc2gsIC1jLCAiZmlyZXdhbGwtY21kIC0tcmVsb2FkIiBdCiMgLSBbIHNoLCAtYywgInl1bSB1cGRhdGUgLXkiXQojIC0gWyBzaCwgLWMsICJzdWRvIHJlYm9vdCIgXQojIC0gWyBzaCwgLWMsICJ5dW0gaW5zdGFsbCAteSBnaXQiXQojIC0gWyBzaCwgLWMsICJta2RpciAtcCAkSE9NRS9nby9zcmMvZ2l0aHViLmNvbS9rZXRpLW9wZW5meCJdCiMgLSBbIHNoLCAtYywgImdpdCBjbG9uZSBodHRwczovL2dpdGh1Yi5jb20va2V0aS1vcGVuZngvb3BlbmZ4LmdpdCAkSE9NRS9nby9zcmMvZ2l0aHViLmNvbS9rZXRpLW9wZW5meCJdCgojaWYgc29tZXRoaW5nIGdvZXMgd3JvbmcgdGhpcyBpcyB0aGUgaXNzdWUKd3JpdGVfZmlsZXM6Ci0gICBjb250ZW50OiB8CiAgICAgICAgIyBNeSBuZXcgL2V0Yy9zeXNjb25maWcvc2FtYmEgZmlsZQogICAgICAgICMKICAgICAgICAjICAgICAgICAgU01CRE9QVElPTlM9Ii1EIgogICAgb3duZXI6IHJvb3Q6cm9vdAogICAgcGF0aDogL2V0Yy9zeXNjb25maWcvNjRiaXRfc3Ryc3RyX3ZpYV82NGJpdF9zdHJzdHJfc3NlMl91bmFsaWduZWQKCnVzZXJzOgogIC0gbmFtZTogY2VudG9zCiAgICBnZWNvczogY2VudG9zCiAgICBwYXNzd29yZDogcGFzc3dvcmQKICAgIGxvY2stcGFzc3dkOiBmYWxzZQogICAgc3VkbzogQUxMPShBTEwpIE5PUEFTU1dEOkFMTAogICAgc3NoX2F1dGhvcml6ZWRfa2V5czoKICAgICAgLSBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUJBUUM1Vm5Xck1kVDVWaWpNa2EyQUtYWmpBZFY5aXljTGg2SFlXY1h5MWRxZW5SZVp1akI5d3dwRGJua1dIVlozako0SS9JWUZyOWNRcE9WQ2x0UzFKVm5wdis3UnRvSFc2Sms4NndVS2lqcTNsU0pYSXJJVW5jYkw4RTluaEFtdHJyV1QrVXhOTG9TdktpTEVhSlRLeFhMTWR6UGhTa3VHTlJLMVlJdlQvVWdpcURmWldMNTdaZlFzU0Roa1NyeExtcHp3aU02WC9qU1l3djdOM1o1TUR5MHZSS25YdWNtenI2ZEs3UXZ1SkdLam1PT1RsaDZDU0NhS2dTRnBLN3dHZHJZTDh4eXhteDNMbWpXZTRUU1FiWWtYQUVZWnNXbWhoZEpoY3dZRHgrbTFwME0zSEZZNFE0bEV6czhLQVV0STRVNy9BL0RubTQxK3haL0JaSkJHY2RHRiByb290QG1hc3RlciAK
